export { BasePage } from './BasePage'
export { LoginPage } from './LoginPage'
export { RegisterPage } from './RegisterPage'
export { DashboardPage } from './DashboardPage'
export { TaskFormModal } from './TaskFormModal'
export { ProductSearchPage } from './ProductSearchPage'
